config/routes.rb
Rails.application.routes.draw do
  resources :styles
  resources :pictures do
    resource :like, only: %i[create destroy]
  end
  resources :museums do
    resource :follow, only: %i[create destroy]
  end

  get 'users/index'
  resources :users, param: :code, only: [:show, :edit, :update, :destroy]
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    # Twitter API認証用
    :omniauth_callbacks => 'users/omniauth_callbacks',
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "users#timeline"
end

app/views/shared/_footer.html.slim
footer.bg-gray-50.text-base
  .container-fluid.py-4.px-6
    span.text-muted Museums &copy; 2022

app/views/shared/_navigation.html.slim
header.w-full.shadow.bg-gray-50.text-base id="app"
  nav.flex.items-center.justify-between.flex-wrap.px-6.py-4 role="navigation" aria-label="Main"
    .flex.items-center.flex-no-shrink.text-gray-700.mr-6
      = link_to 'Museums', '/', class: 'font-semibold text-xl cursor-pointer hover:underline'
    .md:hidden
      button @click="isOpen = !isOpen"
        svg.md:hidden.h-6.w-6.fill-current viewBox="0 0 24 24"
          path v-show="!isOpen" d="M24 6h-24v-4h24v4zm0 4h-24v4h24v-4zm0 8h-24v4h24v-4z"
          path v-show="isOpen"  d="M24 20.188l-8.315-8.209 8.2-8.282-3.697-3.697-8.212 8.318-8.31-8.203-3.666 3.666 8.321 8.24-8.206 8.313 3.666 3.666 8.237-8.318 8.285 8.203z"
    div class="w-full md:flex md:justify-end md:items-center md:w-auto"
      div :class="isOpen ? 'block w-full' : 'hidden'" class="fixed md:flex bg-gray-50"
        = link_to 'Home',     '/',              class: 'block mt-0 md:inline-block text-gray-400 hover:text-gray-500 cursor-pointer mr-4 px-8 py-2 active:bg-gray-400'
        = link_to 'Users',    users_index_path, class: 'block mt-0 md:inline-block text-gray-400 hover:text-gray-500 cursor-pointer mr-4 px-8 py-2 active:bg-gray-400'
        = link_to 'Museums',  museums_path,     class: 'block mt-0 md:inline-block text-gray-400 hover:text-gray-500 cursor-pointer mr-4 px-8 py-2 active:bg-gray-400'
        = link_to 'Pictures', pictures_path,    class: 'block mt-0 md:inline-block text-gray-400 hover:text-gray-500 cursor-pointer mr-4 px-8 py-2 active:bg-gray-400'
        = link_to 'Styles',   styles_path,      class: 'block mt-0 md:inline-block text-gray-400 hover:text-gray-500 cursor-pointer mr-4 px-8 py-2 active:bg-gray-400'
        - if user_signed_in?
          = button_to destroy_user_session_path,  method: :delete,  class: 'block mt-0 md:inline-block text-gray-400 hover:text-gray-500 cursor-pointer mr-4 px-8 py-2 active:bg-gray-400' do
            | ログアウト
            i.fas.fa-right-from-bracket.mr-1.ml-2
        - else
          = button_to new_user_session_path,      method: :get,     class: 'block mt-0 md:inline-block text-gray-400 hover:text-gray-500 cursor-pointer mr-4 px-8 py-2 active:bg-gray-400' do
            | ログイン
            i.fas.fa-right-to-bracket.mr-1.ml-2
javascript:
  var app = new Vue({
    el : '#app',
    data: {
      isOpen: false,
    },
  })