config/routes.rb
Rails.application.routes.draw do
  resources :styles
  resources :pictures do
    resource :like, only: %i[create destroy]
  end
  resources :museums do
    resource :follow, only: %i[create destroy]
  end

  get 'users/index'
  resources :users, param: :code, only: [:show, :edit, :update, :destroy]
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    # Twitter API認証用
    :omniauth_callbacks => 'users/omniauth_callbacks',
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "users#timeline"
end

app/models/style.rb
class Style < ApplicationRecord
  belongs_to :museum
end

app/controllers/styles_controller.rb
class StylesController < ApplicationController
  before_action :set_style, only: %i[ show edit update destroy ]

  # GET /styles or /styles.json
  def index
    @q = Style.ransack(museum_user_id_eq: current_user.try(:id))
    @pagy, @styles = pagy(@q.result)
  end

  # GET /styles/1 or /styles/1.json
  def show
  end

  # GET /styles/new
  def new
    @style = Style.new
  end

  # GET /styles/1/edit
  def edit
  end

  # POST /styles or /styles.json
  def create
    @style = Style.new(style_params)

    respond_to do |format|
      if @style.save
        format.html { redirect_to style_url(@style), notice: "Style was successfully created." }
        format.json { render :show, status: :created, location: @style }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @style.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /styles/1 or /styles/1.json
  def update
    respond_to do |format|
      if @style.update(style_params)
        format.html { redirect_to style_url(@style), notice: "Style was successfully updated." }
        format.json { render :show, status: :ok, location: @style }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @style.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /styles/1 or /styles/1.json
  def destroy
    @style.destroy

    respond_to do |format|
      format.html { redirect_to styles_url, notice: "Style was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_style
      @style = Style.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def style_params
      params.require(:style).permit(:museum_id, :name, :css, :comment)
    end
end

app/helpers/styles_helper.rb
module StylesHelper
end

app/views/styles/_form.html.slim
= simple_form_for(@style) do |f|
  = errors_for(@style)

  .mb-4
    = f.association :museum
  .mb-4
    = f.input :name
  .mb-4
    = f.input :css
  .mb-4
    = f.input :comment

  = f.button :submit, class: 'my-2 bg-blue-500 hover:bg-blue-700 text-white font-bold text-sm py-2 px-4 rounded w-full'

app/views/styles/_style.html.slim
div id="#{dom_id style}"
  p
    strong Museum:
    =< style.museum_id
  p
    strong Name:
    =< style.name
  p
    strong Css:
    =< style.css
  p
    strong Comment:
    =< style.comment

app/views/styles/edit.html.slim
.md:mx-auto.w-full.lg:w-1/2.overflow-hidden.mx-0
  .shadow-md.rounded.px-8.pt-6.pb-8.mb-4.flex.flex-col.justify-center.bg-gray-50
    h2.text-center.text-xl.text-black.mb-3

      = title('Editing Style')
    = render 'form', style: @style

= link_to 'Show', @style
'&nbsp;|
= link_to 'Back', styles_path

app/views/styles/index.html.slim
.flex.flex-row.justify-start.mb-5
  h1.text-xl.text-gray-600.mr-10
    = title('Styles')
  = link_to new_style_path, class: 'px-2 py-1 inline-flex text-xs font-semibold rounded-full bg-green-100 text-green-800 hover:bg-green-200'
    | New Style
    i.fas.fa-circle-plus
div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg"
  table.min-w-full.divide-y.divide-gray-200.border-collapse
    thead.bg-gray-200
      tr
        th.px-3.py-3.text-left.text-xs.font-medium.text-gray-500.uppercase.tracking-wider scope='col' Museum
        th.px-3.py-3.text-left.text-xs.font-medium.text-gray-500.uppercase.tracking-wider scope='col' Name
        th.px-3.py-3.text-left.text-xs.font-medium.text-gray-500.uppercase.tracking-wider scope='col' Css
        th.px-3.py-3.text-left.text-xs.font-medium.text-gray-500.uppercase.tracking-wider scope='col' Comment
        th.px-3.py-3.text-left.text-xs.font-medium.text-gray-500.uppercase.tracking-wider scope='col' colspan='3'
    tbody.bg-white.divide-y.divide-gray-200
      - @styles.each do |style|
        tr.bg-white.hover:bg-blue-50.hover:text-gray-500
          td.px-3.py-3.text-sm.whitespace-nowrap = style.museum.name
          td.px-3.py-3.text-sm.whitespace-nowrap = style.name
          td.px-3.py-3.text-sm.whitespace-nowrap = style.css
          td.px-3.py-3.text-sm.whitespace-nowrap = style.comment
          td.px-3.py-3.text-sm.whitespace-nowrap = link_to 'Show', style, class: 'inline-flex text-xs leading-5 font-semibold text-indigo-500 hover:underline cursor-pointer'
          td.px-3.py-3.text-sm.whitespace-nowrap = link_to 'Edit', edit_style_path(style), class: 'inline-flex text-xs leading-5 font-semibold text-yellow-500 hover:underline cursor-pointer'
          td.px-3.py-3.text-sm.whitespace-nowrap = button_to 'Destroy', style, method: :delete, form: { data: { turbo_confirm: 'Are you sure?' } }, class: 'inline-flex text-xs leading-5 font-semibold text-red-500 hover:underline cursor-pointer'

== pagy_nav(@pagy)

app/views/styles/new.html.slim
.md:mx-auto.w-full.lg:w-1/2.overflow-hidden.mx-0
  .shadow-md.rounded.px-8.pt-6.pb-8.mb-4.flex.flex-col.justify-center.bg-gray-50
    h2.text-center.text-xl.text-black.mb-3

      = title('New Style')

    = render 'form', style: @style
    = link_to 'Back', styles_path

app/views/styles/show.html.slim
h1.text-xl.text-gray-600.mr-10

  = title('Style')

div class="border border-gray-200 my-7 shadow overflow-hidden rounded-sm"
  dl
    div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-4 sm:gap-4 sm:px-6"
      dt.text-sm.font-medium.text-gray-500 Museum
      dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-3" = @style.museum.name
    div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-4 sm:gap-4 sm:px-6"
      dt.text-sm.font-medium.text-gray-500 Name
      dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-3" = @style.name
    div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-4 sm:gap-4 sm:px-6"
      dt.text-sm.font-medium.text-gray-500 Css
      dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-3" = @style.css
    div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-4 sm:gap-4 sm:px-6"
      dt.text-sm.font-medium.text-gray-500 Comment
      dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-3" = @style.comment

= link_to 'Edit', edit_style_path(@style), class: 'hover:underline'
'&nbsp;|
= link_to 'Back', styles_path, class: 'hover:underline'