config/routes.rb
Rails.application.routes.draw do
  resources :styles
  resources :pictures do
    resource :like, only: %i[create destroy]
  end
  resources :museums do
    resource :follow, only: %i[create destroy]
  end

  get 'users/index'
  resources :users, param: :code, only: [:show, :edit, :update, :destroy]
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    # Twitter API認証用
    :omniauth_callbacks => 'users/omniauth_callbacks',
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "users#timeline"
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :museum
  has_many :likes, dependent: :destroy
  has_many :liking_users, through: :likes, source: :user

  mount_uploader :image, ImageUploader

  def liked_by?(user)
    liking_users.include?(user)
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: %i[ show edit update destroy ]

  # GET /pictures or /pictures.json
  def index
    @pictures = Picture.all
    @q = Picture.ransack(museum_user_id_eq: current_user.try(:id))
    @pagy, @pictures = pagy(@q.result)
  end

  # GET /pictures/1 or /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
    @picture.museum_id = params[:museum_id]
  end

  # GET /pictures/1/edit
  def edit
    authorize @picture
  end

  # POST /pictures or /pictures.json
  def create
    @picture = Picture.new(picture_params)

    respond_to do |format|
      if @picture.save
        format.html { redirect_to museum_url(@picture.museum), notice: "Picture was successfully created." }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1 or /pictures/1.json
  def update
    authorize @picture

    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to museum_url(@picture.museum), notice: "Picture was successfully updated." }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1 or /pictures/1.json
  def destroy
    authorize @picture

    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: "Picture was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def picture_params
      params.require(:picture).permit(:museum_id, :name, :image, :comment)
    end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/_form.html.slim
= simple_form_for(@picture) do |f|
  = errors_for(@picture)

  .mb-4
    = f.association :museum, as: :hidden
    = f.input :name
    = f.input :image
    = f.input :comment

  = f.button :submit, class: 'my-2 bg-blue-500 hover:bg-blue-700 text-white font-bold text-sm py-2 px-4 rounded w-full'

app/views/pictures/_picture.html.slim
div id="#{dom_id picture}"

app/views/pictures/_thumb.html.slim
- if picture.present?
  .w-full.h-1/3
    = link_to picture do
      = image_tag picture.image.thumb.url, class: "w-32 h-32 md:w-64 md:h-64 lg:w-96 lg:h-96"
    = render 'likes/like_button', picture: picture, html_id: "like_button_#{picture.id}", count_flg: true

app/views/pictures/edit.html.slim
.md:mx-auto.w-full.lg:w-1/2.overflow-hidden.mx-0
  .shadow-md.rounded.px-8.pt-6.pb-8.mb-4.flex.flex-col.justify-center.bg-gray-50
    h2.text-center.text-xl.text-black.mb-3

      = title('Editing Picture')
    = render 'form', picture: @picture

app/views/pictures/index.html.slim
.flex.flex-row.justify-start.mb-5
  h1.text-xl.text-gray-600.mr-10
    = title('Pictures')
  = link_to new_picture_path, class: 'px-2 py-1 inline-flex text-xs font-semibold rounded-full bg-green-100 text-green-800 hover:bg-green-200'
    | New Picture
    i.fas.fa-circle-plus
div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg"
  table.min-w-full.divide-y.divide-gray-200.border-collapse
    thead.bg-gray-200
      tr
        th.px-3.py-3.text-left.text-xs.font-medium.text-gray-500.uppercase.tracking-wider scope='col' Museum
        th.px-3.py-3.text-left.text-xs.font-medium.text-gray-500.uppercase.tracking-wider scope='col' Name
        th.px-3.py-3.text-left.text-xs.font-medium.text-gray-500.uppercase.tracking-wider scope='col' Image
        th.px-3.py-3.text-left.text-xs.font-medium.text-gray-500.uppercase.tracking-wider scope='col' Comment
        th.px-3.py-3.text-left.text-xs.font-medium.text-gray-500.uppercase.tracking-wider scope='col' colspan='4'
    tbody.bg-white.divide-y.divide-gray-200
      - @pictures.each do |picture|
        tr.bg-white.hover:bg-blue-50.hover:text-gray-500
          td.px-3.py-3.text-sm.whitespace-nowrap = picture.museum.name
          td.px-3.py-3.text-sm.whitespace-nowrap = picture.name
          td.px-3.py-3.text-sm.whitespace-nowrap = picture.image
          td.px-3.py-3.text-sm.whitespace-nowrap = picture.comment
          td.px-3.py-3.text-sm.whitespace-nowrap = link_to 'Show', picture, class: 'inline-flex text-xs leading-5 font-semibold text-indigo-500 hover:underline cursor-pointer'
          td.px-3.py-3.text-sm.whitespace-nowrap = link_to 'Edit', edit_picture_path(picture), class: 'inline-flex text-xs leading-5 font-semibold text-yellow-500 hover:underline cursor-pointer'
          td.px-3.py-3.text-sm.whitespace-nowrap = button_to 'Destroy', picture, method: :delete, form: { data: { turbo_confirm: 'Are you sure?' } }, class: 'inline-flex text-xs leading-5 font-semibold text-red-500 hover:underline cursor-pointer'
          td.px-3.py-3.text-sm.whitespace-nowrap
            = render 'likes/like_button', picture: picture, html_id: "like_button_#{picture.id}", count_flg: true

== pagy_nav(@pagy)

app/views/pictures/new.html.slim
.md:mx-auto.w-full.lg:w-1/2.overflow-hidden.mx-0
  .shadow-md.rounded.px-8.pt-6.pb-8.mb-4.flex.flex-col.justify-center.bg-gray-50
    h2.text-center.text-xl.text-black.mb-3

      = title('New Picture')

    = render 'form', picture: @picture
    = link_to 'Back', pictures_path

app/views/pictures/show.html.slim
h1.text-xl.text-gray-600.mr-10

  = title('Picture')

div class="border border-gray-200 my-7 shadow overflow-hidden rounded-sm"
  dl
    div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-4 sm:gap-4 sm:px-6"
      dt.text-sm.font-medium.text-gray-500 Museum
      dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-3" = @picture.museum.name
    div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-4 sm:gap-4 sm:px-6"
      dt.text-sm.font-medium.text-gray-500 Name
      dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-3" = @picture.name
    div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-4 sm:gap-4 sm:px-6"
      dt.text-sm.font-medium.text-gray-500 Image 
      dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-3" = @picture.image
    div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-4 sm:gap-4 sm:px-6"
      dt.text-sm.font-medium.text-gray-500 Comment
      dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-3" = @picture.comment

= link_to 'Edit', edit_picture_path(@picture), class: 'hover:underline'