config/routes.rb
Rails.application.routes.draw do
  resources :styles
  resources :pictures do
    resource :like, only: %i[create destroy]
  end
  resources :museums do
    resource :follow, only: %i[create destroy]
  end

  get 'users/index'
  resources :users, param: :code, only: [:show, :edit, :update, :destroy]
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    # Twitter API認証用
    :omniauth_callbacks => 'users/omniauth_callbacks',
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "users#timeline"
end

app/models/museum.rb
class Museum < ApplicationRecord
  belongs_to :user
  has_many :pictures, dependent: :destroy
  has_many :follows, dependent: :destroy
  has_many :following_users, through: :follows, source: :user

  def followed_by?(user)
    following_users.include?(user)
  end

end

app/controllers/museums_controller.rb
class MuseumsController < ApplicationController
  before_action :set_museum, only: %i[ show edit update destroy follow]

  # GET /museums or /museums.json
  def index
    @q = Museum.ransack()
    @pagy, @museums = pagy(@q.result)
  end

  # GET /museums/1 or /museums/1.json
  def show
  end

  # GET /museums/new
  def new
    @museum = Museum.new
  end

  # GET /museums/1/edit
  def edit
    authorize @museum
  end

  # POST /museums or /museums.json
  def create
    @museum = Museum.new(museum_params)
    @museum.user = current_user

    respond_to do |format|
      if @museum.save
        format.html { redirect_to museum_url(@museum), notice: "Museum was successfully created." }
        format.json { render :show, status: :created, location: @museum }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @museum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /museums/1 or /museums/1.json
  def update
    authorize @museum

    respond_to do |format|
      if @museum.update(museum_params)
        format.html { redirect_to museum_url(@museum), notice: "Museum was successfully updated." }
        format.json { render :show, status: :ok, location: @museum }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @museum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /museums/1 or /museums/1.json
  def destroy
    authorize @museum

    @museum.destroy
    respond_to do |format|
      format.html { redirect_to museums_url, notice: "Museum was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_museum
      @museum = Museum.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def museum_params
      params.require(:museum).permit(:name, :open_start_at, :open_end_at, :comment)
    end
end

app/helpers/museums_helper.rb
module MuseumsHelper
end

app/views/museums/_form.html.slim
= simple_form_for(@museum) do |f|
  = errors_for(@museum)

  .mb-4
    = f.input :name
    = f.input :open_start_at
    = f.input :open_end_at
    = f.input :comment

  = f.button :submit, class: 'my-2 bg-blue-500 hover:bg-blue-700 text-white font-bold text-sm py-2 px-4 rounded w-full'

app/views/museums/_museum.html.slim
div id="#{dom_id museum}"
  p
    strong Name:
    =< museum.name

app/views/museums/edit.html.slim
.md:mx-auto.w-full.lg:w-1/2.overflow-hidden.mx-0
  .shadow-md.rounded.px-8.pt-6.pb-8.mb-4.flex.flex-col.justify-center.bg-gray-50
    h2.text-center.text-xl.text-black.mb-3
      Museums
    = render 'form', museum: @museum

= link_to 'Show', @museum
'&nbsp;|
= link_to 'Back', museums_path

app/views/museums/index.html.slim
.flex.flex-row.justify-start.mb-5
  h1.text-xl.text-gray-600.mr-10
    = title('Museums')
  = link_to new_museum_path, class: 'px-2 py-1 inline-flex text-xs font-semibold rounded-full bg-green-100 text-green-800 hover:bg-green-200'
    | New Museum
    i.fas.fa-circle-plus
div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg"
  table.min-w-full.divide-y.divide-gray-200.border-collapse
    thead.bg-gray-200
      tr
        th.px-3.py-3.text-left.text-xs.font-medium.text-gray-500.uppercase.tracking-wider scope='col'
          | Name
        th.px-3.py-3.text-left.text-xs.font-medium.text-gray-500.uppercase.tracking-wider scope='col'
          | Open
        th.px-3.py-3.text-left.text-xs.font-medium.text-gray-500.uppercase.tracking-wider scope='col' colspan='4'
    tbody.bg-white.divide-y.divide-gray-200
      - @museums.each do |museum|
        tr.bg-white.hover:bg-blue-50.hover:text-gray-500
          td.px-3.py-3.text-sm.whitespace-nowrap
            = museum.name
          td.px-3.py-3.text-sm.whitespace-nowrap
            = museum.decorate.open_at_range
          td.px-3.py-3.text-sm.whitespace-nowrap
            = link_to 'Show', museum, class: 'inline-flex text-xs leading-5 font-semibold text-indigo-500 hover:underline cursor-pointer'
          td.px-3.py-3.text-sm.whitespace-nowrap
            = link_to 'Edit', edit_museum_path(museum), class: 'inline-flex text-xs leading-5 font-semibold text-yellow-500 hover:underline cursor-pointer'
          td.px-3.py-3.text-sm.whitespace-nowrap
            = button_to 'Destroy', museum, method: :delete, form: { data: { turbo_confirm: 'Are you sure?' } }, class: 'inline-flex text-xs leading-5 font-semibold text-red-500 hover:underline cursor-pointer'
          td.px-3.py-3.text-sm.whitespace-nowrap
            = render 'follows/follow_button', museum: museum, html_id: "follow_button_#{museum.id}"

== pagy_nav(@pagy)

app/views/museums/new.html.slim
.md:mx-auto.w-full.lg:w-1/2.overflow-hidden.mx-0
  .shadow-md.rounded.px-8.pt-6.pb-8.mb-4.flex.flex-col.justify-center.bg-gray-50
    h2.text-center.text-xl.text-black.mb-3
      | New Museums

    = render 'form', museum: @museum
    = link_to 'Back', museums_path

app/views/museums/show.html.slim
div class="border border-gray-200 shadow overflow-hidden rounded-sm"
  header
    div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-4 sm:gap-4 sm:px-6"
      div class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-3" = @museum.name
    div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-4 sm:gap-4 sm:px-6"
      div class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-3"
        = @museum.decorate.open_at_range
  div
    artcle
      div
        - pictures = @museum.pictures
        - for idx in 0..pictures.size do
          - p idx
          - p pictures[idx]
          - if idx % 3 == 0
            div class="flex justify-between flex-wrap"
              div class="w-1/3 h-full"
                = render "pictures/thumb", picture: pictures[idx]
              div class="w-1/3 h-full"
                = render "pictures/thumb", picture: pictures[idx+1]
              div class="w-1/3 h-full"
                = render "pictures/thumb", picture: pictures[idx+2]
          - idx += 3

= link_to new_picture_path(museum_id: @museum.id), class: 'px-2 py-1 inline-flex text-xs font-semibold rounded-full bg-green-100 text-green-800 hover:bg-green-200'
  | New Picture
  i.fas.fa-circle-plus